apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secret.secretKey | quote }}
  DATABASE_PASSWORD: {{ .Values.secret.databasePassword | quote }}
